# Generated by Django 3.2.16 on 2022-10-08 09:53

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_type', models.SmallIntegerField(choices=[(1, '博客站'), (2, '考研站'), (5, '自由站'), (4, '番号站')], unique=True, verbose_name='站点')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.IntegerField(choices=[(1, 'category'), (2, 'page'), (3, 'custom')], verbose_name='分类类型')),
                ('title', models.CharField(max_length=16, verbose_name='分类')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('index', models.SmallIntegerField(default=1, verbose_name='目录顺序')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='url')),
                ('icon', models.CharField(blank=True, max_length=20, null=True, verbose_name='icon')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加日期')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='contents.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_category', to='contents.blogtype', verbose_name='站点')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='CommonLinkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, '左邻右舍'), (2, '旗下网站'), (3, '工具网站'), (4, '优秀博客')], verbose_name='友链类型')),
                ('name', models.CharField(max_length=100, verbose_name='网站标题')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='网站描述')),
                ('url', models.URLField(verbose_name='网站链接')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='avatar')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='标签')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加日期')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_tag', to='contents.blogtype', verbose_name='站点')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=50, verbose_name='top栏')),
                ('copyright', models.CharField(max_length=100, verbose_name='版权')),
                ('title', models.CharField(max_length=20, verbose_name='网站名称')),
                ('site_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='网站描述')),
                ('html_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='desc')),
                ('ad_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='引流')),
                ('notice', models.TextField(verbose_name='公众内容')),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='关于')),
                ('avatar', models.ImageField(upload_to='', verbose_name='头像')),
                ('wechat', models.ImageField(upload_to='', verbose_name='公众号')),
                ('keywords', models.CharField(blank=True, max_length=100, null=True, verbose_name='key')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contents.blogtype', verbose_name='站点')),
            ],
            options={
                'verbose_name': '信息',
                'verbose_name_plural': '信息',
            },
        ),
        migrations.CreateModel(
            name='SayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='说说内容')),
                ('add_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='说说日期')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contents.blogtype', verbose_name='站点')),
            ],
            options={
                'verbose_name': '说说',
                'verbose_name_plural': '说说',
            },
        ),
        migrations.CreateModel(
            name='RecommendPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SmallIntegerField(unique=True)),
                ('link_post', models.TextField(verbose_name='推荐')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommend_introduce', to='contents.blogtype', verbose_name='站点')),
            ],
            options={
                'verbose_name': '推荐',
                'verbose_name_plural': '推荐',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, '博客站'), (2, '考研站'), (5, '自由站'), (4, '番号站')], verbose_name='站点')),
                ('nickname', models.CharField(default='嘉美伯爵', max_length=12, verbose_name='作者')),
                ('title', models.CharField(max_length=250, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('raw_url', models.URLField(blank=True, null=True, verbose_name='原文地址')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='post/%Y/%m/%d', verbose_name='封面')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('digg_count', models.IntegerField(default=0, verbose_name='点赞量')),
                ('share_count', models.IntegerField(default=0, verbose_name='分享量')),
                ('collect_count', models.IntegerField(default=0, verbose_name='收藏量')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('update_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_pass', models.BooleanField(verbose_name='是否过审')),
                ('recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('comment_status', models.BooleanField(default=True, verbose_name='评论状态')),
                ('status', models.IntegerField(choices=[(0, '停用'), (1, '在用')], default=1, verbose_name='状态')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_post', to='contents.category', verbose_name='分类')),
                ('tag', models.ManyToManyField(related_name='tag_post', to='contents.Tag', verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ('create_at',),
            },
        ),
        migrations.CreateModel(
            name='LinkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='网站标题')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='网站描述')),
                ('url', models.URLField(verbose_name='网站链接')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_link', to='contents.blogtype', verbose_name='站点')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
            },
        ),
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('update_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新日期')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_introduce', to='contents.blogtype', verbose_name='站点')),
            ],
            options={
                'verbose_name': '介绍',
                'verbose_name_plural': '介绍',
            },
        ),
        migrations.CreateModel(
            name='CarouselPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carouse/%Y/%m/%d', verbose_name='轮播图(800*200)广告(360*120)')),
                ('url', models.URLField(blank=True, null=True, verbose_name='图片网址')),
                ('index', models.IntegerField(default=1, verbose_name='轮播顺序')),
                ('type', models.SmallIntegerField(default=0, verbose_name='图片类型')),
                ('title', models.CharField(max_length=100, verbose_name='desc')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel', to='contents.siteinfo', verbose_name='站点广告')),
            ],
            options={
                'verbose_name': '轮播',
                'verbose_name_plural': '轮播',
            },
        ),
    ]
