# Generated by Django 3.2.16 on 2022-10-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_type', models.SmallIntegerField(unique=True, verbose_name='站点')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_category', to='contents.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='introduce',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_introduce', to='contents.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='linkinfo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_link', to='contents.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='recommendpost',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommend_introduce', to='contents.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='sayinfo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contents.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contents.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_tag', to='contents.site', verbose_name='站点'),
        ),
        migrations.DeleteModel(
            name='BlogType',
        ),
    ]
