# Generated by Django 3.2.16 on 2022-10-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20221019_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='blog_type',
        ),
        migrations.AddField(
            model_name='site',
            name='title',
            field=models.CharField(default=None, max_length=100, verbose_name='站点'),
            preserve_default=False,
        ),
    ]
